title: Exoplanetas Club de Astronom√≠a
description: Actividad del Club de Astro sobre exoplanetas
theme: just-the-docs

url: https://LudCano.github.io/exoplanetas-club
logo: "/figs/logo_club.png"
search_enabled: false
